### ISSUE TITLE
Error with command: npm install

### ISSUE THREAD

**Issue by mohamedmehdigara** [buckyroberts/React-Boilerplate#8]
PS C:\Users\p-c\Downloads\Github\React-Boilerplate-1> npm install
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use 
Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive 
security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\p-c\\Downloads\\Github\\React-Boilerplate-1\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.15.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher 
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\graceful-fs\polyfills.js:306:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\p-c\\Downloads\\Github\\React-Boilerplate-1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-sass  
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\p-c\AppData\Local\npm-cache\_logs\2022-05-26T09_35_02_184Z-debug-0.log    
PS C:\Users\p-c\Downloads\Github\React-Boilerplate-1> npm install --force
npm WARN using --force Recommended protections disabled.
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use 
Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive 
security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\p-c\\Downloads\\Github\\React-Boilerplate-1\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.15.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\graceful-fs\polyfills.js:306:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\p-c\\Downloads\\Github\\React-Boilerplate-1\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\p-c\Downloads\Github\React-Boilerplate-1\node_modules\node-sass  
npm ERR! gyp ERR! node -v v16.15.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

**Comment by Michael1142** [comment]
Hi @mohamedmehdigara and anyone else who runs into this problem. 👋 

I ran into this issue myself. 

Essentially, what is happening is you're using a much newer version of node which is incompatible with this repos package.json file.

For what it's worth this is quite an old tutorial and I think the state of react has moved on greatly since Bucky made this series so you might be better off finding a more recent tutorial. 

If you're truly desperate to get this repo working you need to install a contemporary version of node which for June 2016 was [6.2.1](https://nodejs.org/en/download/releases/) (FYI at time of writing in September 2022 the latest version is 18.8.0.)

If you're looking to have multiple node installs on your machine I'd recommend using nvm [Node Version Manager].

Once you've installed the dependencies from the package.json file you'll need to install the gulp-cli to get the next step int the readme file to work. 

```
npm install --global gulp-cli
```

I hope this helps unstick anyone who runs into this issue. 😃
